### ISSUE TITLE
android bug when using Tinder motion - bug de android no de tinder motion

### ISSUE THREAD

**Issue by fllaryora** [rodrigomartind/TinderMotionLayout#1]
Hi, Rodrigo tanks for teaching Motions

By setting huge size of text and high contrast color letters
you are able to go to details page only for the first card, after liking or unliking your tab event will be ignored.

Thanks
Si se pone la app en letras grandes y alto contraste .
Solo se va al modo detalle en la primera card, en el resto de las cards se ignora el tap.
Gracias Rodrigo!

**Comment by fllaryora** [comment]
DAdo que es algo de Android y no del projecto lo cierro.

**Comment by rodrigomartind** [comment]
Gracias por escribir, tengo desactualizado este repo. Sorry
